import pandas as pd # type: ignore
import numpy as np # type: ignore
from sklearn.ensemble import RandomForestClassifier # type: ignore
import joblib # type: ignore
import random

# 1. Synthesize a CSV representing thousands of mocked test-taker logs
def generate_training_data(rows=2000):
    data = []
    for _ in range(rows):
        tabs = random.randint(0, 12)
        idle = random.randint(0, 150)
        face = random.randint(0, 20)
        clicks = random.randint(0, 5)
        
        # Ground-truth Pseudo Labeling Logic indicating teacher interventions
        if tabs == 0 and idle <= 5 and face <= 1 and clicks == 0:
            risk = 0 # Class 0 (Green): Ideal student
        elif tabs <= 1 and idle <= 15 and face <= 3 and clicks == 0:
            risk = 1 # Class 1 (Yellow): Slightly suspicious / accidental
        elif tabs <= 3 and idle <= 45 and face <= 6 and clicks <= 1:
            risk = 2 # Class 2 (Orange): High risk / intentional looking away
        else:
            risk = 3 # Class 3 (Red): Critical / obvious cheating behavior
            
        data.append([tabs, idle, face, clicks, risk])
    return pd.DataFrame(data, columns=['tab_switches', 'idle_seconds', 'face_warnings', 'right_clicks', 'risk_level'])

if __name__ == '__main__':
    df = generate_training_data()
    df.to_csv('behavior_logs.csv', index=False)
    print("Autogenerated 'behavior_logs.csv' for Random Forest training!")

    # 2. Train Random Forest 
    X = df[['tab_switches', 'idle_seconds', 'face_warnings', 'right_clicks']]
    y = df['risk_level']

    print("Training Decision Trees...")
    clf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
    clf.fit(X, y)

    # 3. Export the `.pkl`
    joblib.dump(clf, 'proctor_ml_model.pkl')
    print("Successfully output 'proctor_ml_model.pkl'! Flask is now predicting in real-time.")
